apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-app
  namespace: helm-app
spec:
  project: default
  source:
    repoURL: https://github.com/aselnur/python-chart.git
    path: helm-chart
    targetRevision: 'master'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'helm-app'
  syncPolicy:
    automated:
      prune: false
      selfHeal: true