apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 8.5.1
    chart: grafana
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'grafana'
  syncPolicy:
    automated:
      prune: false
      selfHeal: true