apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  labels:
{{- include "commonLabels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    - port: {{ .Values.servicePort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
{{- include "commonLabels" . | nindent 4 }}
